---
title: "기업 HR데이터를 이용한 근속률/영향요인 분석"
author: "ITS 정혜지, PPC 이혜림"
date: '2020 4 20 '
output: html_document
---

# 1.	개발 개요/목적/효과 (Outline of the Development / Objective / Effectiveness)
<ul> ①	지난 OO년 간 임직원들의 입, 퇴사 기록을 다각도로 시각화하여 근속률에 영향을 미칠 수 있는 요소를 분석 </ul>
<ul> ②	영향을 미치는 요소를 파악하여 추후 실데이터를 매핑하여법인 근속률 향상에 도움 </ul> 
<ul> ③	타법인과의 비교를 활용하여 KPMG만의 차별성 파악
 </ul> 
# 2.	Application Owner & 사용대상자(Target User)
<ul> ①	Application Owner : PPC & ITS  </ul>
<ul> ②	Target User : All user </ul>

# 3.	시스템 설명 및 요구 사항 (System Description & Requirement) 
<ul> ①	개발 형태 – Report 형식의 Dashboard </ul>
<ul> ②	데이터 분류 </ul>

  1. 전체 임직원 근속률
      *	학력 별(학교별, 국내/국외) 근속률
      *	년도, 성별, 본부 별 근속률
      *	휴가 사용빈도, 근로시간에 따른 근속률
      * 직무별 교육 기회에 따른 근속률
      * 해외파견, 휴직 여부에 따른 근속률
      * 결혼 여부에 따른 근속률
      * 고과평가, 평가등급, 포상 및 징계 여부에 따른 근속률
      * 경력 년수 대비 이직 횟수에 따른 근속률
      * 연봉인상률 및 연봉


  2.  재직자 만족도
    - 업무별
    - 부서 및 직무별
    - 직장 내 관계


  3. 타법인과의 비교 
    -	추후 반영 가능성 여부 논의 중


<ul> ③	데이터 출처</ul>

 - IBS HR Analysis data from Kaggle

<ul> ④	R (tidyverse..), 웹 (Shiny ..) , Crawling 시 Python 활용 예정</ul>

  4.  모델링
   * 로지스틱 회귀분석을 이용하여 근속률에 대한 확률 도출
   * 확률에 큰 영향을 미치는 요인 도출


# 4.	업무 프로세스 및 개발 관점에서 고려사항(Consideration from Business Process and Development’s View)

<ul> ①	모델링 기법에 대한 기본 지식 학습 필요 </ul>
<ul> ②	분석 데이터를 실제 법인데이터로 응용할 수 있는 형태로 구성 필요</ul>
<ul> ③	...  </ul>


# 5.  작업 계획

 - 5.11 > 주제 및 Dataset 선정 완료: 데이터 구조 분석
 - 5.20 > Web에 Shiny Dashboard 배포하여 결과물의 Prototype 도출 (with Sample graphs)
 - 5.25 > 데이터 분석 및 매핑 

 - 6.20 > 완료
